- name: install apache and php packages
  package:
    name:
      - "{{ apache_package }}"
      - "{{ php_package }}"
    state: latest

- name: start and enable apache service
  tags: apache,httpd
  service: 
    name: "{{ apache_service }}"
    state: started
    enable: yes

- name: change e-mail address for admin
  tags: httpd
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin test@mail.net
  when: ansible_distribution == "CentOS"
  notify: restart_apache

- name: copy default html for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644